In [2]:
import pandas as pd
schools = pd.read_csv("schools.csv")
schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7

In [28]:
best_math_schools = schools[schools["average_math"]>=640][["school_name","average_math"]].sort_values("average_math",ascending=False)
best_math_schools

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641

In [29]:
schools["total_SAT"] = schools["average_math"] + schools["average_reading"] + schools["average_writing"]
schools

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1,1261
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9,1529
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7,1197
...,...,...,...,...,...,...,...,...
370,"Queens High School for Information, Research, ...",Queens,Q465,372,362,352,44.6,1086
371,Rockaway Park High School for Environmental Su...,Queens,Q410,357,381,376,38.5,1114
372,Channel View School for Research,Queens,Q410,427,430,423,76.6,1280
373,Rockaway Collegiate High School,Queens,Q410,399,403,405,46.5,1207
374,Scholars' Academy,Queens,Q180,588,560,568,99.2,1716

In [30]:
top_10_schools = schools[["school_name","total_SAT"]].sort_values("total_SAT",ascending=False).head(10)
top_10_schools

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

In [20]:
boroughs = schools.groupby("borough")["total_SAT"].agg(["count","mean","std"]).round(2)
boroughs

               count     mean     std
borough
Bronx             98  1202.72  150.39
Brooklyn         109  1230.26  154.87
Manhattan         89  1340.13  230.29
Queens            69  1345.48  195.25
Staten Island     10  1439.00  222.30

In [31]:
largest_std_dev = boroughs[boroughs["std"]==boroughs["std"].max()]
largest_std_dev

           count     mean     std
borough
Manhattan     89  1340.13  230.29

In [32]:
largest_std_dev = large_std_dev.rename(columns={"count":"num_schools","mean":"average_SAT","std":"std_SAT"})
largest_std_dev

           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29